name = "QuadMeshGame"
uuid = "b8dfd2ad-ed09-4480-aaba-9cf555b7c6b8"
authors = ["Arjun <arjun.narayanan91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
